/**
 * Redis-backed state for Programmatic Tool Calling (PTC) replay mode.
 *
 * Owns every key the replay path mutates:
 *   - `exec_state:<id>`        ExecutionState (request inputs + bookkeeping)
 *   - `tool_history:<id>`      Hash of cached tool results, keyed by call_id
 *   - `exec_lock:<id>`         Per-execution mutex protecting the above pair
 *   - `exec_result:<id>`       Blocking-mode terminal result (kept here so
 *                              blocking and replay share one cleanup path)
 *
 * The router (`programmatic-router.ts`) orchestrates HTTP routing and sandbox
 * iteration; this module owns everything between the router and Redis. All
 * functions here are pure with respect to module-level state and side-effect
 * free outside Redis itself, so they can be exercised directly by unit tests
 * with an `ioredis-mock` connection.
 *
 * NOTE: `cleanupStaleExecutions` is exported but the periodic janitor
 * `setInterval` is registered in the router on import; importing this module
 * for tests does NOT start a background timer.
 */

import axios from 'axios';
import { nanoid } from 'nanoid';
import type { Redis } from 'ioredis';
import type * as t from '../types';
import type { LCTool } from '../preamble';
import { connection } from '../queue';
import { env } from '../config';
import { internalServiceHeaders } from '../internal-service-auth';
import logger from '../logger';
import {
  ptcReplayHistorySize,
  ptcReplayHistoryEntries,
  ptcReplayStaleCleanups,
} from '../metrics';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

export const EXECUTION_STATE_TTL = 600;
export const MAX_REPLAY_CALLS = 200;

/** Cap on the serialized `exec_state:<id>` JSON blob (request inputs +
 * bookkeeping: `userCode`, `tools` schema, input `files`, `emittedCallIds`,
 * counters — does NOT include tool outputs, those live in `tool_history:`).
 * Sized to comfortably absorb realistic LLM-generated code plus a handful of
 * input files; the per-result and aggregate `tool_history` caps below scale
 * proportionally. */
export const MAX_EXECUTION_STATE_BYTES = 10_000_000;

/** Per-execution continuation lock TTL. Must exceed the worst-case sandbox
 * run (`env.JOB_TIMEOUT`) plus bookkeeping overhead, otherwise the lock can
 * expire while the holder is still executing and a second continuation
 * would be able to mutate `tool_history`/`exec_state` concurrently. Floor
 * at 10 minutes so short job timeouts don't produce a tiny lock window. */
export const REPLAY_LOCK_TTL_MS = Math.max(10 * 60 * 1000, env.JOB_TIMEOUT * 2 + 30_000);

/** Per-entry cap for a single serialized tool result (JSON bytes). Keeps the
 * Redis hash and the `_ptc_history.json` injected into the sandbox bounded
 * regardless of how pathological a single tool result is. Scaled
 * proportionally with `MAX_EXECUTION_STATE_BYTES` (ratio 1:2 vs exec_state). */
export const MAX_TOOL_RESULT_BYTES = 5_000_000;

/** Aggregate cap across ALL results persisted for a single execution. Scaled
 * proportionally with `MAX_EXECUTION_STATE_BYTES` (ratio 4:1 vs exec_state)
 * so a long replay flow can accumulate ~8 saturating tool results before
 * being asked to break work into a fresh execution. */
export const MAX_TOOL_HISTORY_TOTAL_BYTES = 40_000_000;

/** Maximum number of keys `scanKeys` will return in a single call. The janitor
 * runs every `STALE_CLEANUP_INTERVAL` and processes whatever this yields; if
 * Redis is genuinely backed up with `exec_state:*` entries beyond this cap,
 * the next tick will pick up the rest. The point is to avoid an unbounded
 * in-memory array on a degenerate Redis instance, NOT to throttle work. */
export const SCAN_KEYS_DEFAULT_LIMIT = 10_000;

/** Replay call_ids are generated by the sandbox as zero-padded 3-digit
 * counters (`call_001`...); we allow up to 6 digits of slack so future
 * cap bumps don't require a regex change, but cap length so a client
 * can't submit pathologically long ids that would bloat Redis hash
 * field names beyond what `MAX_TOOL_RESULT_BYTES` or the aggregate cap
 * would catch (those bound values, not keys). */
export const CALL_ID_RE = /^call_\d{3,6}$/;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ExecutionState {
  execution_id: string;
  session_id: string;
  sessionKey?: string;
  userId: string;
  tenantId?: string;
  canonicalUserId?: string;
  orgId?: string;
  serviceId?: string;
  externalUserId?: string;
  principalSource?: string;
  authContextHash?: string;
  /** Optional even though current construction sites always set a string,
   *  because `ExecutionState` is JSON-deserialized from Redis and entries
   *  persisted by prior binaries (or future schema migrations) can omit
   *  it. The two continuation paths intentionally bypass the apiKeyId
   *  ownership check when the persisted value is missing — see
   *  `checkContinuationPreconditions` and the blocking continuation auth
   *  in `programmatic-router.ts`. Tighten on both paths in a follow-up
   *  after one `EXECUTION_STATE_TTL` window post a trusted-source
   *  apiKeyId invariant. */
  apiKeyId?: string;
  startTime: number;
  /**
   * Wall-clock ms of the last interaction that advanced this execution (initial
   * submit, continuation accept, or sandbox iteration finish). Used by the
   * stale-execution sweeper so long-running but still-active replay flows
   * aren't reaped purely based on total age.
   */
  lastActivity?: number;
  mode: 'blocking' | 'replay';
  /** Replay-only: persisted so continuations can re-enqueue without the client re-sending code. */
  userCode?: string;
  tools?: LCTool[];
  files?: t.RequestFile[];
  isPyPlot?: boolean;
  timeout?: number;
  callCount?: number;
  /** Running total of bytes persisted into `tool_history:<execution_id>`.
   * Tracked so continuations can reject oversized histories without scanning
   * the full hash on every request. */
  historyBytes?: number;
  /** Cumulative set of call_ids ever emitted by the sandbox for this
   * execution, serialized as an array. Used to reject incoming
   * `tool_results` entries whose `call_id` was never actually requested
   * — a buggy or malicious client could otherwise pre-seed arbitrary
   * ids (e.g. `call_042`) that later replay iterations would consume
   * as cache hits and skip real tool calls. Populated in `runAndRespond`
   * right before emitting a `tool_call_required` response. */
  emittedCallIds?: string[];
  /** Replay-only: metadata for emitted tool calls, keyed by `id` at use sites.
   * Stored so continuation commits can persist the original tool name and a
   * compact input signature beside the result. Bash replay uses that metadata
   * to safely resolve background tool calls whose completion order can differ
   * between runs. */
  emittedToolCalls?: Array<{
    id: string;
    name: string;
    input_hash?: string;
    call_site?: string;
  }>;
  /** Target language for PTC. Defaults to 'python'. Bash is replay-only. */
  language?: 'python' | 'bash';
  /** Blocking-only legacy fields. New blocking results live in
   * `exec_result:<id>` (see setBlockingResult); `jobResult` is kept on the
   * interface only as a deploy-time fallback so executions whose state was
   * persisted by an older binary still resolve correctly while in-flight. */
  jobCompleted?: boolean;
  jobResult?: t.ExecuteResult;
  jobError?: string;
}

export interface HistoryEntry {
  result: unknown;
  is_error?: boolean;
  error_message?: string;
  received_at: number;
  tool_name?: string;
  input_hash?: string;
  call_site?: string;
}

/** Describes how an incoming `tool_results` batch would interact with the
 * already-persisted history for the same execution. Computed BEFORE any
 * Redis mutation so the caller can cheaply enforce caps without risking a
 * half-applied update. */
export interface ToolHistoryDelta {
  /** Serialized entries keyed by call_id, ready to pass to `HSET`. */
  serializedByCallId: Map<string, string>;
  /** Call_ids that weren't previously persisted. */
  newCallIds: string[];
  /** Signed byte delta this batch would apply to the aggregate history
   * size: `sum(newEntryBytes)` for new call_ids plus
   * `sum(newEntryBytes - oldEntryBytes)` for overwrites. Negative when a
   * retry shrinks a previously-persisted entry. */
  bytesDelta: number;
}

/** Thrown by `setExecutionState` / `commitToolHistoryAndState` when the
 * serialized blob would exceed `MAX_EXECUTION_STATE_BYTES`. Distinct from
 * a generic `Error` so callsites can map this to a deterministic
 * client-facing 413 instead of letting the top-level router handler turn
 * it into a generic 500 — the typical trigger is a large but otherwise
 * valid request, which is a client/input sizing problem, not a server
 * failure. */
export class ExecutionStateTooLargeError extends Error {
  readonly bytes: number;
  readonly cap: number;
  constructor(execution_id: string, bytes: number, cap: number) {
    super(`ExecutionState for ${execution_id} is ${bytes} bytes, exceeds cap ${cap}`);
    this.name = 'ExecutionStateTooLargeError';
    this.bytes = bytes;
    this.cap = cap;
  }
}

// ---------------------------------------------------------------------------
// Test seam
// ---------------------------------------------------------------------------

/** Lua scripts cached on the client via `defineCommand` so each call site
 * issues `EVALSHA` (with auto `SCRIPT LOAD` fallback) instead of paying the
 * Lua compile + parse cost of `EVAL` on every invocation. Scripts:
 *
 *   - `releaseExecutionLockScript`  CAS-DEL on the lock key (only the holder
 *                                   may release it — guards stale releases).
 *   - `setExecutionResultScript`    EXISTS-then-dual-SET (state + result)
 *                                   so a concurrent `cleanupExecution` can't
 *                                   resurrect an orphan `exec_result` blob.
 *   - `setExecutionErrorScript`     EXISTS-then-SET (state) — same race
 *                                   guard for the error path.
 *
 * Note: `ioredis-mock` implements `defineCommand` and routes through its
 * Lua runner, but its Lua coverage is a subset of real Redis (notably
 * partial `redis.call` arg parsing); the integration suite still runs
 * against a real Redis container so any divergence surfaces there. */
type RedisWithScripts = Redis & {
  releaseExecutionLockScript(lockKey: string, token: string): Promise<number>;
  setExecutionResultScript(
    stateKey: string,
    resultKey: string,
    stateJson: string,
    resultJson: string,
    ttlSeconds: string,
  ): Promise<number>;
  setExecutionErrorScript(
    stateKey: string,
    stateJson: string,
    ttlSeconds: string,
  ): Promise<number>;
};

const SCRIPTS_REGISTERED = Symbol.for('replay-state.scriptsRegistered');

function registerScripts(client: Redis): RedisWithScripts {
  const tagged = client as Redis & { [SCRIPTS_REGISTERED]?: true };
  if (tagged[SCRIPTS_REGISTERED]) return client as RedisWithScripts;
  client.defineCommand('releaseExecutionLockScript', {
    numberOfKeys: 1,
    lua: "if redis.call('get', KEYS[1]) == ARGV[1] then return redis.call('del', KEYS[1]) else return 0 end",
  });
  client.defineCommand('setExecutionResultScript', {
    numberOfKeys: 2,
    lua: `if redis.call('exists', KEYS[1]) == 1 then
  redis.call('set', KEYS[1], ARGV[1], 'EX', ARGV[3])
  redis.call('set', KEYS[2], ARGV[2], 'EX', ARGV[3])
  return 1
else
  return 0
end`,
  });
  client.defineCommand('setExecutionErrorScript', {
    numberOfKeys: 1,
    lua: `if redis.call('exists', KEYS[1]) == 1 then
  redis.call('set', KEYS[1], ARGV[1], 'EX', ARGV[2])
  return 1
else
  return 0
end`,
  });
  tagged[SCRIPTS_REGISTERED] = true;
  return client as RedisWithScripts;
}

/** Module-level Redis handle. Defaults to the shared queue connection so
 * production code paths are unchanged; tests can swap in an `ioredis-mock`
 * instance via `setRedisForTests()` to exercise the pure replay-state logic
 * without spinning up real Redis or the queue subsystem. */
let redis: RedisWithScripts = registerScripts(connection);

/** Replace the Redis handle used by every function in this module. Intended
 * ONLY for unit tests; production code should never call this. The pair
 * `setRedisForTests`/`resetRedisForTests` lets a test suite isolate per-test
 * keyspaces by handing in fresh mock instances. */
export function setRedisForTests(client: Redis): void {
  redis = registerScripts(client);
}

/** Restore the production Redis handle. Useful after a test suite finishes
 * so accidental reuse doesn't leak a closed mock connection. */
export function resetRedisForTests(): void {
  redis = registerScripts(connection);
}

// ---------------------------------------------------------------------------
// Execution state CRUD
// ---------------------------------------------------------------------------

/** Entries persisted by pre-rename binaries stored the legacy `chcUserId` (leak-check:allow)
 *  key; normalize on read. Safe to delete one EXECUTION_STATE_TTL window
 *  after the external_user_id rollout. */
export function normalizeExecutionState(state: ExecutionState): ExecutionState {
  const legacy = (state as Record<string, unknown>)['chcUserId']; // leak-check:allow
  if (state.externalUserId == null && typeof legacy === 'string') {
    state.externalUserId = legacy;
  }
  return state;
}

export async function getExecutionState(execution_id: string): Promise<ExecutionState | null> {
  const data = await redis.get(`exec_state:${execution_id}`);
  return data != null ? normalizeExecutionState(JSON.parse(data) as ExecutionState) : null;
}

export async function setExecutionState(state: ExecutionState): Promise<void> {
  const serialized = JSON.stringify(state);
  const serializedBytes = Buffer.byteLength(serialized, 'utf8');
  if (serializedBytes > MAX_EXECUTION_STATE_BYTES) {
    throw new ExecutionStateTooLargeError(
      state.execution_id,
      serializedBytes,
      MAX_EXECUTION_STATE_BYTES,
    );
  }
  await redis.set(
    `exec_state:${state.execution_id}`,
    serialized,
    'EX',
    EXECUTION_STATE_TTL,
  );
}

export async function deleteExecutionState(execution_id: string): Promise<void> {
  await redis.del(`exec_state:${execution_id}`);
}

// ---------------------------------------------------------------------------
// Per-execution lock
// ---------------------------------------------------------------------------

/**
 * Acquires an exclusive per-execution lock via Redis `SET NX EX`. Returns the
 * lock token on success (used to release only the current holder) or `null` if
 * another request holds the lock. Prevents TOCTOU on concurrent continuations.
 */
export async function acquireExecutionLock(execution_id: string): Promise<string | null> {
  const token = nanoid();
  const result = await redis.set(
    `exec_lock:${execution_id}`,
    token,
    'PX',
    REPLAY_LOCK_TTL_MS,
    'NX',
  );
  return result === 'OK' ? token : null;
}

export async function releaseExecutionLock(execution_id: string, token: string): Promise<void> {
  try {
    await redis.releaseExecutionLockScript(`exec_lock:${execution_id}`, token);
  } catch (err) {
    logger.warn('Failed to release exec lock', { execution_id, err });
  }
}

// ---------------------------------------------------------------------------
// Generic key scan helper
// ---------------------------------------------------------------------------

/** Iterate matching Redis keys with SCAN instead of the blocking KEYS command.
 * Stops collecting once `limit` keys have been gathered to keep the array
 * bounded on degenerate datasets. */
export async function scanKeys(
  match: string,
  count = 200,
  limit = SCAN_KEYS_DEFAULT_LIMIT,
): Promise<string[]> {
  const stream = redis.scanStream({ match, count });
  const out: string[] = [];
  for await (const batch of stream as AsyncIterable<string[]>) {
    for (const key of batch) {
      out.push(key);
      if (out.length >= limit) {
        stream.destroy();
        logger.warn('scanKeys hit limit; remaining keys deferred to next pass', {
          match, limit,
        });
        return out;
      }
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Blocking-mode terminal result
// ---------------------------------------------------------------------------

/** Blocking-mode result key. The full `t.ExecuteResult` (stdout / stderr /
 * file refs) lives here, separate from `exec_state:`, because a successful
 * blocking run with large stdout/stderr or many file refs can serialize past
 * the `MAX_EXECUTION_STATE_BYTES` cap; storing the result inline used to
 * make `setExecutionState` throw, which was caught downstream and reported
 * as `status: error` even though the sandbox succeeded. Capping the result
 * blob would cause the same misclassification, so we instead let Redis
 * itself bound the value (per-key, default 512 MB) — the tighter cap remains
 * on the lighter `exec_state:` blob the replay path mutates on every
 * continuation. */
function blockingResultKey(execution_id: string): string {
  return `exec_result:${execution_id}`;
}

export async function setBlockingResult(execution_id: string, result: t.ExecuteResult): Promise<void> {
  await redis.set(
    blockingResultKey(execution_id),
    JSON.stringify(result),
    'EX',
    EXECUTION_STATE_TTL,
  );
}

export async function getBlockingResult(execution_id: string): Promise<t.ExecuteResult | null> {
  const data = await redis.get(blockingResultKey(execution_id));
  return data != null ? (JSON.parse(data) as t.ExecuteResult) : null;
}

export async function deleteBlockingResult(execution_id: string): Promise<void> {
  await redis.del(blockingResultKey(execution_id));
}

/** Persist the terminal result of a blocking execution.
 *
 * The blocking-mode HTTP handler polls Tool Call Server for completion and
 * tears down state via `cleanupExecution` once it sees `completed`; meanwhile
 * a separate BullMQ `waitUntilFinished(...).then(setExecutionResult)`
 * callback fires when the underlying sandbox job resolves. If cleanup wins
 * the race, naively writing `exec_result:<id>` (and re-writing
 * `exec_state:<id>` with `jobCompleted=true`) would resurrect a torn-down
 * execution and leave both blobs orphaned until `EXECUTION_STATE_TTL` —
 * a real memory-pressure risk under load with large stdout/stderr.
 *
 * The Lua script atomically checks that `exec_state:<id>` still exists
 * and, only if so, writes BOTH the updated state (with `jobCompleted=true`)
 * and the result blob in a single hop. If cleanup has already removed the
 * state, the entire update is skipped. */
export async function setExecutionResult(execution_id: string, result: t.ExecuteResult): Promise<void> {
  const stateKey = `exec_state:${execution_id}`;
  const resultKey = `exec_result:${execution_id}`;
  const existing = await getExecutionState(execution_id);
  if (!existing) return;
  const updated: ExecutionState = { ...existing, jobCompleted: true, jobResult: undefined };
  const updatedSerialized = JSON.stringify(updated);
  if (Buffer.byteLength(updatedSerialized, 'utf8') > MAX_EXECUTION_STATE_BYTES) {
    throw new ExecutionStateTooLargeError(
      execution_id,
      Buffer.byteLength(updatedSerialized, 'utf8'),
      MAX_EXECUTION_STATE_BYTES,
    );
  }
  /** EXISTS-then-SET both keys atomically so a concurrent
   * `cleanupExecution` racing between our `getExecutionState` above and
   * the writes below cannot leave an orphan blob behind. The Lua body
   * is registered on the client via `defineCommand`. */
  await redis.setExecutionResultScript(
    stateKey,
    resultKey,
    updatedSerialized,
    JSON.stringify(result),
    String(EXECUTION_STATE_TTL),
  );
}

export async function setExecutionError(execution_id: string, error: Error): Promise<void> {
  const stateKey = `exec_state:${execution_id}`;
  const existing = await getExecutionState(execution_id);
  if (!existing) return;
  const updated: ExecutionState = { ...existing, jobCompleted: true, jobError: error.message };
  const serialized = JSON.stringify(updated);
  if (Buffer.byteLength(serialized, 'utf8') > MAX_EXECUTION_STATE_BYTES) {
    throw new ExecutionStateTooLargeError(
      execution_id,
      Buffer.byteLength(serialized, 'utf8'),
      MAX_EXECUTION_STATE_BYTES,
    );
  }
  /** Same race window as `setExecutionResult`: a `cleanupExecution`
   * winning between our `getExecutionState` and the write would
   * otherwise resurrect torn-down state. The conditional SET makes
   * the write a no-op once the execution has been cleaned up. */
  await redis.setExecutionErrorScript(stateKey, serialized, String(EXECUTION_STATE_TTL));
}

// ---------------------------------------------------------------------------
// Tool history (replay mode)
// ---------------------------------------------------------------------------

export function historyKey(execution_id: string): string {
  return `tool_history:${execution_id}`;
}

/** Canonical byte-comparable form of the "semantic" fields of a history
 * entry. Excludes `received_at` so the stored wall-clock stamp from the
 * first write doesn't poison comparison against a genuinely identical
 * retry. Key order matches the construction order below on both sides,
 * which is sufficient for checking equality of payloads produced from
 * the same client-supplied object. */
function canonicalEntryBody(
  result: unknown,
  isError: boolean | undefined,
  errorMessage: string | undefined,
): string {
  return JSON.stringify({
    result,
    is_error: isError ?? false,
    error_message: errorMessage,
  });
}

/** Compute the delta between an incoming result batch and the persisted
 * history hash. Does not mutate Redis. Must be called under the per-
 * execution lock so the snapshot of existing keys is stable until the
 * subsequent `HSET`. Enforces:
 *
 *  - `MAX_TOOL_RESULT_BYTES` on the full serialized entry (result +
 *    is_error + error_message + metadata) so callers can't sneak
 *    oversized payloads in via `error_message` or other envelope fields
 *    while the raw `result` stays under the cap;
 *  - *Immutability* of already-persisted call_ids. Replay determinism
 *    depends on the history being append-only: a reusable continuation
 *    token combined with a mutable history would let a stale retry
 *    rewrite `call_001`'s result after later rounds have advanced,
 *    causing the next iteration to diverge from what the token was
 *    issued against. Overlapping call_ids are accepted only when the
 *    incoming payload is byte-identical to the stored one (true
 *    idempotent retry); otherwise the whole batch is rejected with a
 *    409-style mismatch error and no Redis mutation is attempted.
 */
export async function computeToolHistoryDelta(
  execution_id: string,
  results: Array<{
    call_id: string;
    result: unknown;
    is_error?: boolean;
    error_message?: string;
    tool_name?: string;
    input_hash?: string;
    call_site?: string;
  }>,
): Promise<ToolHistoryDelta | { error: string; status?: number }> {
  const serializedByCallId = new Map<string, string>();
  if (results.length === 0) {
    return { serializedByCallId, newCallIds: [], bytesDelta: 0 };
  }
  const key = historyKey(execution_id);
  const callIds = results.map(r => r.call_id);
  const existingRaw = callIds.length > 0 ? await redis.hmget(key, ...callIds) : [];
  const oldByCallId = new Map<string, { entry: HistoryEntry; bytes: number }>();
  for (let i = 0; i < callIds.length; i++) {
    const raw = existingRaw[i];
    if (typeof raw !== 'string') continue;
    try {
      const parsed = JSON.parse(raw) as HistoryEntry;
      oldByCallId.set(callIds[i], {
        entry: parsed,
        bytes: Buffer.byteLength(raw, 'utf8'),
      });
    } catch {
      logger.warn('Malformed existing tool_history entry; treating as absent', {
        execution_id,
        call_id: callIds[i],
      });
    }
  }
  const now = Date.now();
  const newCallIds: string[] = [];
  let bytesDelta = 0;
  for (const r of results) {
    const entry: HistoryEntry = {
      result: r.result,
      is_error: r.is_error ?? false,
      error_message: r.error_message,
      received_at: now,
      tool_name: r.tool_name,
      input_hash: r.input_hash,
      call_site: r.call_site,
    };
    const serialized = JSON.stringify(entry);
    const newBytes = Buffer.byteLength(serialized, 'utf8');
    if (newBytes > MAX_TOOL_RESULT_BYTES) {
      return {
        error: `tool_results[${r.call_id}] serialized entry is ${newBytes} bytes, exceeds per-entry cap ${MAX_TOOL_RESULT_BYTES}`,
      };
    }
    const existing = oldByCallId.get(r.call_id);
    if (existing) {
      const incomingBody = canonicalEntryBody(r.result, r.is_error, r.error_message);
      const storedBody = canonicalEntryBody(
        existing.entry.result,
        existing.entry.is_error,
        existing.entry.error_message,
      );
      if (incomingBody !== storedBody) {
        return {
          status: 409,
          error: `tool_results[${r.call_id}] has already been recorded with a different payload; replay history is immutable`,
        };
      }
      continue;
    }
    serializedByCallId.set(r.call_id, serialized);
    newCallIds.push(r.call_id);
    bytesDelta += newBytes;
  }
  return { serializedByCallId, newCallIds, bytesDelta };
}

/** Commit a previously-computed history delta AND the updated execution
 * state atomically in a single Redis `MULTI`/`EXEC` transaction. Either
 * both mutations land or neither does — closes the split-brain where a
 * successful `HSET` followed by a failed `SET` would leave counters
 * stale and subsequent retries would be treated as no-ops. The state
 * blob must already be validated against `MAX_EXECUTION_STATE_BYTES`
 * before this is called; failure is logged and propagated. */
export async function commitToolHistoryAndState(
  state: ExecutionState,
  delta: ToolHistoryDelta,
): Promise<void> {
  const serialized = JSON.stringify(state);
  const serializedBytes = Buffer.byteLength(serialized, 'utf8');
  if (serializedBytes > MAX_EXECUTION_STATE_BYTES) {
    /** Use the typed error so the continuation handler can distinguish
     * a sizing problem (-> 413) from a generic Redis transaction failure
     * (-> 503). A plain `Error` here would bubble through to the top-level
     * router catch as an opaque 500. */
    throw new ExecutionStateTooLargeError(
      state.execution_id,
      serializedBytes,
      MAX_EXECUTION_STATE_BYTES,
    );
  }
  const hKey = historyKey(state.execution_id);
  const sKey = `exec_state:${state.execution_id}`;
  const tx = redis.multi();
  if (delta.serializedByCallId.size > 0) {
    const kvs: string[] = [];
    for (const [callId, s] of delta.serializedByCallId) {
      kvs.push(callId, s);
    }
    tx.hset(hKey, ...kvs);
  }
  /** Refresh the history-hash TTL on every commit, including idempotent
   * retries where `delta.serializedByCallId` is empty. Without this, a
   * retry near TTL expiry renews `exec_state` (via the `SET EX` below)
   * but leaves `tool_history` on its original expiry; a slow next
   * sandbox run could then span the history's original TTL and cause
   * subsequent continuations to load an empty history and re-emit
   * already-resolved tool calls. `EXPIRE` on a missing hash is a safe
   * no-op. */
  tx.expire(hKey, EXECUTION_STATE_TTL);
  tx.set(sKey, serialized, 'EX', EXECUTION_STATE_TTL);
  const results = await tx.exec();
  if (!results) {
    throw new Error(`Redis transaction aborted for execution ${state.execution_id}`);
  }
  for (const [err] of results) {
    if (err) {
      throw err;
    }
  }
  /** Observe the size and entry-count of the persisted history *after*
   * commit succeeds so failed commits don't pollute the histogram with
   * sizes that never made it to Redis. `historyBytes` and `callCount`
   * have already been advanced on `state` to reflect the post-commit
   * truth, so they're the right values to record. */
  ptcReplayHistorySize.observe(state.historyBytes ?? 0);
  ptcReplayHistoryEntries.observe(state.callCount ?? 0);
}

/** Extend the Redis TTL on both the execution-state blob and the tool-history
 * hash so a slow client doesn't end up with a split-brain where the token is
 * still valid but prior tool results have already expired, which would force
 * the sandbox to re-emit earlier calls on replay. */
export async function refreshExecutionTtl(execution_id: string): Promise<void> {
  await Promise.all([
    redis.expire(`exec_state:${execution_id}`, EXECUTION_STATE_TTL),
    redis.expire(historyKey(execution_id), EXECUTION_STATE_TTL),
  ]);
}

export async function loadToolHistory(execution_id: string): Promise<Record<string, HistoryEntry>> {
  const raw = await redis.hgetall(historyKey(execution_id));
  const out: Record<string, HistoryEntry> = {};
  for (const [k, v] of Object.entries(raw)) {
    try {
      out[k] = JSON.parse(v) as HistoryEntry;
    } catch {
      logger.warn('Dropping malformed tool_history entry', { execution_id, call_id: k });
    }
  }
  return out;
}

export async function deleteToolHistory(execution_id: string): Promise<void> {
  await redis.del(historyKey(execution_id));
}

// ---------------------------------------------------------------------------
// Cleanup
// ---------------------------------------------------------------------------

/** Number of `exec_state:*` keys to fetch per `MGET` round-trip during the
 * stale-execution sweep. Sized so a full sweep over 10,000 keys takes ~50
 * round-trips instead of 10,000 — plenty of pipelining headroom while
 * keeping each Redis reply bounded by typical TCP/MTU windows. */
const CLEANUP_BATCH_SIZE = 200;

export async function cleanupStaleExecutions(): Promise<number> {
  try {
    const keys = await scanKeys('exec_state:*');
    if (keys.length === 0) return 0;
    const now = Date.now();
    let cleaned = 0;

    /** Batch the per-key state reads via `MGET` so a sweep over many
     * exec_state keys completes in O(keys / batch) Redis round-trips
     * rather than O(keys) sequential `GET`s. The decision-and-delete
     * step still iterates per-execution because the deletes (history,
     * blocking result, tool_call_server session, exec_state key) are
     * heterogeneous and each touches different Redis keyspaces. */
    for (let offset = 0; offset < keys.length; offset += CLEANUP_BATCH_SIZE) {
      const batchKeys = keys.slice(offset, offset + CLEANUP_BATCH_SIZE);
      const values = await redis.mget(...batchKeys);
      for (let i = 0; i < batchKeys.length; i++) {
        const data = values[i];
        if (data == null) continue;

        let state: ExecutionState;
        try {
          state = JSON.parse(data) as ExecutionState;
        } catch {
          /** Malformed JSON in `exec_state:<id>` (corrupt write or partial
           * legacy migration) — drop it AND its sibling `tool_history` /
           * `exec_result` keys instead of breaking the whole sweep.
           * Earlier we only dropped `exec_state` here, leaving siblings
           * orphaned until their independent Redis TTL fired (up to
           * `EXECUTION_STATE_TTL` of wasted memory per malformed key).
           * The execution id is encoded in the key suffix; we can't
           * recover the typed state, but we don't need to in order to
           * scope the targeted deletes.
           *
           * Counted toward `cleaned` and logged at warn level so a burst
           * of malformed keys (corrupt writes, mid-deploy migrations) is
           * visible to operators via both `ptc_replay_stale_cleanups_total`
           * and structured logs, instead of silently disappearing. */
          const orphanId = batchKeys[i].slice('exec_state:'.length);
          logger.warn('Reaping malformed exec_state and sibling keys', {
            execution_id: orphanId,
          });
          await Promise.all([
            redis.del(batchKeys[i]),
            deleteToolHistory(orphanId),
            deleteBlockingResult(orphanId),
          ]).catch(err => {
            logger.warn('Sibling delete failed during malformed-key cleanup', {
              execution_id: orphanId,
              error: err instanceof Error ? err.message : String(err),
            });
          });
          cleaned++;
          continue;
        }
        const lastActivity = state.lastActivity ?? state.startTime;
        const idle = now - lastActivity;

        if (idle > EXECUTION_STATE_TTL * 1000 && state.jobCompleted !== true) {
          logger.warn('Cleaning up stale execution', {
            execution_id: state.execution_id,
            idleSeconds: idle / 1000,
            totalAgeSeconds: (now - state.startTime) / 1000,
            mode: state.mode,
          });

          if (state.mode === 'blocking') {
            await axios.delete(`${env.TOOL_CALL_SERVER_URL}/sessions/${state.execution_id}`, {
              headers: internalServiceHeaders(),
            })
              .catch(() => {});
          }
          await Promise.all([
            deleteToolHistory(state.execution_id),
            deleteBlockingResult(state.execution_id),
            redis.del(batchKeys[i]),
          ]);
          cleaned++;
        }
      }
    }

    if (cleaned > 0) {
      logger.info(`Cleaned up ${cleaned} stale executions`);
      ptcReplayStaleCleanups.inc(cleaned);
    }
    return cleaned;
  } catch (error) {
    logger.error('Error cleaning up stale executions:', error);
    return 0;
  }
}

export async function cleanupExecution(execution_id: string, mode: 'blocking' | 'replay'): Promise<void> {
  try {
    const ops: Array<Promise<unknown>> = [
      deleteExecutionState(execution_id),
      deleteToolHistory(execution_id),
      deleteBlockingResult(execution_id),
    ];
    if (mode === 'blocking') {
      ops.push(
        axios.delete(`${env.TOOL_CALL_SERVER_URL}/sessions/${execution_id}`, {
          headers: internalServiceHeaders(),
        }).catch(() => {}),
      );
    }
    await Promise.all(ops);
    logger.info('Execution cleanup completed', { execution_id, mode });
  } catch (error) {
    logger.error('Error during execution cleanup:', { execution_id, error });
  }
}

// ---------------------------------------------------------------------------
// Tool result validation
// ---------------------------------------------------------------------------

/**
 * Validate the shape of a single `tool_results` entry. Prevents garbage
 * (null, wrong types, bad call_ids) from being persisted into Redis history.
 */
export function validateToolResult(
  r: unknown,
):
  | { call_id: string; result: unknown; is_error?: boolean; error_message?: string }
  | { error: string } {
  if (r == null || typeof r !== 'object' || Array.isArray(r)) {
    return { error: 'tool_results entries must be objects' };
  }
  const obj = r as Record<string, unknown>;
  const callId = obj.call_id;
  if (typeof callId !== 'string' || !CALL_ID_RE.test(callId)) {
    return { error: `tool_results[].call_id must match /^call_\\d{3,6}$/, got: ${JSON.stringify(callId)}` };
  }
  if (!('result' in obj)) {
    return { error: `tool_results[${callId}].result is required` };
  }
  if (obj.is_error !== undefined && typeof obj.is_error !== 'boolean') {
    return { error: `tool_results[${callId}].is_error must be a boolean if present` };
  }
  if (obj.error_message !== undefined && typeof obj.error_message !== 'string') {
    return { error: `tool_results[${callId}].error_message must be a string if present` };
  }
  let resultSerialized: string | undefined;
  try {
    resultSerialized = JSON.stringify(obj.result);
  } catch (err) {
    return { error: `tool_results[${callId}].result is not JSON-serializable` };
  }
  /** `JSON.stringify` only throws on circular references; for `undefined`,
   * functions, and `Symbol` it returns the JS value `undefined` rather
   * than the string `'undefined'`. The earlier `?? 'null'` fallback
   * silently coerced these to a 4-byte placeholder and accepted them
   * as valid history entries — but the entry would then deserialize
   * to `null` on replay, drifting from what the client originally
   * sent. Reject explicitly so callers get a clear error. */
  if (resultSerialized === undefined) {
    return {
      error: `tool_results[${callId}].result is not JSON-serializable (got undefined / function / symbol)`,
    };
  }
  const resultBytes = Buffer.byteLength(resultSerialized, 'utf8');
  if (resultBytes > MAX_TOOL_RESULT_BYTES) {
    return {
      error: `tool_results[${callId}].result is ${resultBytes} bytes, exceeds per-result cap ${MAX_TOOL_RESULT_BYTES}`,
    };
  }
  return {
    call_id: callId,
    result: obj.result,
    is_error: obj.is_error as boolean | undefined,
    error_message: obj.error_message as string | undefined,
  };
}

// ---------------------------------------------------------------------------
// Continuation pre-checks (pure)
// ---------------------------------------------------------------------------

export interface ValidatedContinuationResult {
  call_id: string;
  result: unknown;
  is_error?: boolean;
  error_message?: string;
  tool_name?: string;
  input_hash?: string;
  call_site?: string;
}

/** Validate the raw `tool_results` array a continuation request submitted:
 * batch-cap, per-entry shape (via `validateToolResult`), and call_id
 * uniqueness within the batch. Pure; no Redis. Extracted from the router
 * so the branch coverage is unit-testable.
 */
export function validateContinuationBatch(tool_results: unknown[]):
  | { ok: true; results: ValidatedContinuationResult[] }
  | { ok: false; status: number; error: string } {
  if (tool_results.length > MAX_REPLAY_CALLS) {
    return {
      ok: false,
      status: 400,
      error: `tool_results has ${tool_results.length} entries; the per-batch cap is ${MAX_REPLAY_CALLS}`,
    };
  }
  const results: ValidatedContinuationResult[] = [];
  const seen = new Set<string>();
  for (const raw of tool_results) {
    const v = validateToolResult(raw);
    if ('error' in v) {
      return { ok: false, status: 400, error: v.error };
    }
    if (seen.has(v.call_id)) {
      return {
        ok: false,
        status: 400,
        error: `Duplicate call_id in tool_results: ${v.call_id}`,
      };
    }
    seen.add(v.call_id);
    results.push({
      call_id: v.call_id,
      result: v.result,
      is_error: v.is_error,
      error_message: v.error_message,
    });
  }
  return { ok: true, results };
}

/** Apply the post-state-load pre-checks to a continuation request:
 * mode, ownership/auth, that every incoming call_id was actually emitted
 * by the sandbox, and the projected aggregate caps after applying
 * `delta`. Pure; no Redis. The caller still owns the side effect of
 * cleaning up an over-cap execution (`MAX_REPLAY_CALLS`) — surfaced via
 * `cleanupOnReject: true` — because cleanup needs the lock and the live
 * Redis client.
 */
export function checkContinuationPreconditions(params: {
  state: ExecutionState;
  results: ValidatedContinuationResult[];
  userId: string;
  apiKeyId?: string;
  tenantId?: string;
  authContextHash?: string;
  delta: ToolHistoryDelta;
}):
  | { ok: true }
  | { ok: false; status: number; error: string; cleanupOnReject?: boolean } {
  const { state, results, userId, apiKeyId, tenantId, authContextHash, delta } = params;
  if (state.mode !== 'replay') {
    return {
      ok: false,
      status: 400,
      error: 'Execution was started in blocking mode; continuation mode mismatch',
    };
  }
  if (
    state.userId !== userId ||
    (state.apiKeyId != null && state.apiKeyId !== apiKeyId) ||
    (state.tenantId != null && state.tenantId !== tenantId) ||
    (state.authContextHash != null && state.authContextHash !== authContextHash)
  ) {
    return { ok: false, status: 403, error: 'Forbidden' };
  }
  const issued = new Set(state.emittedCallIds ?? []);
  for (const r of results) {
    if (!issued.has(r.call_id)) {
      return {
        ok: false,
        status: 400,
        error: `tool_results[${r.call_id}] was not issued by the sandbox for this execution`,
      };
    }
  }
  if ((state.callCount ?? 0) + delta.newCallIds.length > MAX_REPLAY_CALLS) {
    return {
      ok: false,
      status: 400,
      error: `Execution exceeded maximum tool calls (${MAX_REPLAY_CALLS})`,
      cleanupOnReject: true,
    };
  }
  const projectedHistoryBytes = (state.historyBytes ?? 0) + delta.bytesDelta;
  if (projectedHistoryBytes > MAX_TOOL_HISTORY_TOTAL_BYTES) {
    return {
      ok: false,
      status: 400,
      error: `Aggregate tool_history for this execution would be ${projectedHistoryBytes} bytes, exceeds cap ${MAX_TOOL_HISTORY_TOTAL_BYTES}`,
    };
  }
  return { ok: true };
}
